//------------------------------------------------------------------------------
//
// Copyright (C) 2006, Xilinx, Inc. All Rights Reserved.
//
// This file is owned and controlled by Xilinx and must be used solely
// for design, simulation, implementation and creation of design files
// limited to Xilinx devices or technologies. Use with non-Xilinx
// devices or technologies is expressly prohibited and immediately
// terminates your license.
//
// Xilinx products are not intended for use in life support
// appliances, devices, or systems. Use in such applications is
// expressly prohibited.
//
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor      : Xilinx
// \   \   \/     Version     : 1.2
//  \   \         Application : Generated by Xilinx PCI Express Wizard
//  /   /         Filename    : tb_def.v
// /___/   /\     Module      : not applicable
// \   \  /  \
//  \___\/\___\
//
//------------------------------------------------------------------------------
`timescale 1 ns / 10 ps

`define TB_USER_TIMEOUT          100000
`define TB_LINK_NEG_TIMEOUT      200000

`define BUFFER_DEPTH 1050 //70

`define CAP_ID_PM      1
`define CAP_ID_AGP     2
`define CAP_ID_VPD     3
`define CAP_ID_SLOT    4
`define CAP_ID_MSI     5
`define CAP_ID_HOTSWAP 6
`define CAP_ID_PCIE    16
                       
`define CAP_ID_AER     1
`define CAP_ID_VC      2
`define CAP_ID_DSN     3
`define CAP_ID_PB      4

// User Read/Write CONSTANTS
`define TC_SELECT_0              3'b000
`define TC_SELECT_1              3'b001
`define TC_SELECT_2              3'b010
`define TC_SELECT_3              3'b011
`define TC_SELECT_4              3'b100
`define TC_SELECT_5              3'b101
`define TC_SELECT_6              3'b110
`define TC_SELECT_7              3'b111

`define FIFO_SELECT_POSTED       2'b00
`define FIFO_SELECT_NON_POSTED   2'b01
`define FIFO_SELECT_COMPLETION   2'b10
`define FIFO_SELECT_CONFIG       2'b11

`define CHECK_MODE_AVAILABLE     0
`define CHECK_MODE_PARTIAL       1

`define READ_MODE_NORMAL         0
`define READ_MODE_PARTIAL        1
`define READ_MODE_PARTIAL_BIT    0
`define READ_MODE_RETRY          2 // will keep retrying reads until successful
`define READ_MODE_RETRY_BIT      1

`define WRITE_MODE_NORMAL        0
`define WRITE_MODE_DISCARD       1
`define WRITE_MODE_DISCARD_BIT   0
`define WRITE_MODE_COMPLETE      2
`define WRITE_MODE_COMPLETE_BIT  1
`define WRITE_MODE_ECRC          4 // will assert tx_complete on the first data word
`define WRITE_MODE_ECRC_BIT      2

`define WAIT_STATE_0  0
`define WAIT_STATE_1  1
`define WAIT_STATE_2  2
`define WAIT_STATE_3  3
